#!/usr/bin/python3

import sys
import datetime

template = """# {date}

## Notas
- """

file_name = sys.argv[1].rsplit("/")[-1].replace('.md', '')
date = datetime.datetime.strptime(file_name, "%Y-%m-%d")

print(template.format(date=date.strftime("%d/%m/%Y")))
